Tidy up the Mac Catalyst support

diff --git a/patch/mpdecimal.patch b/patch/mpdecimal.patch
--- a/patch/mpdecimal.patch
+++ b/patch/mpdecimal.patch
@@ -1,21 +1,410 @@
-diff -ur mpdecimal-4.0.0-orig/config.sub mpdecimal-4.0.0/config.sub
---- mpdecimal-4.0.0-orig/config.sub	2024-01-10 08:25:00
-+++ mpdecimal-4.0.0/config.sub	2024-07-24 13:16:35
-@@ -1127,7 +1127,7 @@
+diff -Naur mpdecimal-4.0.0-orig/config.sub mpdecimal-4.0.0/config.sub
+--- mpdecimal-4.0.0-orig/config.sub	2024-01-10 00:25:00
++++ mpdecimal-4.0.0/config.sub	2025-02-23 20:09:01
+@@ -1,10 +1,11 @@
+ #! /bin/sh
+ # Configuration validation subroutine script.
+-#   Copyright 1992-2023 Free Software Foundation, Inc.
++#   Copyright 1992-2024 Free Software Foundation, Inc.
+ 
+ # shellcheck disable=SC2006,SC2268 # see below for rationale
+ 
+-timestamp='2023-07-31'
++# Patched 2024-02-03 to include support for arm64_32 and iOS/tvOS/watchOS simulators
++timestamp='2024-01-01'
+ 
+ # This file is free software; you can redistribute it and/or modify it
+ # under the terms of the GNU General Public License as published by
+@@ -76,7 +77,7 @@
+ version="\
+ GNU config.sub ($timestamp)
+ 
+-Copyright 1992-2023 Free Software Foundation, Inc.
++Copyright 1992-2024 Free Software Foundation, Inc.
+ 
+ This is free software; see the source for copying conditions.  There is NO
+ warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
+@@ -1127,7 +1128,7 @@
  	xscale-* | xscalee[bl]-*)
  		cpu=`echo "$cpu" | sed 's/^xscale/arm/'`
  		;;
 -	arm64-* | aarch64le-*)
-+	arm64-* | arm64_32-* | aarch64le-*)
++	arm64-* | aarch64le-* | arm64_32-*)
  		cpu=aarch64
  		;;
  
-@@ -1792,6 +1792,8 @@
- 	os2-emx)
+@@ -1177,11 +1178,11 @@
+ 
+ 	*)
+ 		# Recognize the canonical CPU types that are allowed with any
+-		# company name (aarch64c added by mpdecimal project).
++		# company name.
+ 		case $cpu in
+ 			1750a | 580 \
+ 			| a29k \
+-			| aarch64 | aarch64_be | aarch64c \
++			| aarch64 | aarch64_be | aarch64c | arm64ec \
+ 			| abacus \
+ 			| alpha | alphaev[4-8] | alphaev56 | alphaev6[78] \
+ 			| alpha64 | alpha64ev[4-8] | alpha64ev56 | alpha64ev6[78] \
+@@ -1200,6 +1201,7 @@
+ 			| d10v | d30v | dlx | dsp16xx \
+ 			| e2k | elxsi | epiphany \
+ 			| f30[01] | f700 | fido | fr30 | frv | ft32 | fx80 \
++			| javascript \
+ 			| h8300 | h8500 \
+ 			| hppa | hppa1.[01] | hppa2.0 | hppa2.0[nw] | hppa64 \
+ 			| hexagon \
+@@ -1221,6 +1223,7 @@
+ 			| moxie \
+ 			| mt \
+ 			| msp430 \
++			| nanomips* \
+ 			| nds32 | nds32le | nds32be \
+ 			| nfp \
+ 			| nios | nios2 | nios2eb | nios2el \
+@@ -1252,6 +1255,7 @@
+ 			| ubicom32 \
+ 			| v70 | v850 | v850e | v850e1 | v850es | v850e2 | v850e2v3 \
+ 			| vax \
++			| vc4 \
+ 			| visium \
+ 			| w65 \
+ 			| wasm32 | wasm64 \
+@@ -1284,11 +1288,12 @@
+ 
+ # Decode manufacturer-specific aliases for certain operating systems.
+ 
+-if test x$basic_os != x
++if test x"$basic_os" != x
+ then
+ 
+ # First recognize some ad-hoc cases, or perhaps split kernel-os, or else just
+ # set os.
++obj=
+ case $basic_os in
+ 	gnu/linux*)
+ 		kernel=linux
+@@ -1488,10 +1493,16 @@
+ 			os=eabi
+ 			;;
+ 		    *)
+-			os=elf
++			os=
++			obj=elf
+ 			;;
+ 		esac
  		;;
- 	*-eabi* | *-gnueabi*)
++	aout* | coff* | elf* | pe*)
++		# These are machine code file formats, not OSes
++		obj=$os
++		os=
 +		;;
-+	ios*-simulator | tvos*-simulator | watchos*-simulator | ios*-macabi )
+ 	*)
+ 		# No normalization, but not necessarily accepted, that comes below.
  		;;
- 	none-coff* | none-elf*)
+@@ -1510,12 +1521,15 @@
+ # system, and we'll never get to this point.
+ 
+ kernel=
++obj=
+ case $cpu-$vendor in
+ 	score-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	spu-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	*-acorn)
+ 		os=riscix1.2
+@@ -1525,28 +1539,35 @@
+ 		os=gnu
+ 		;;
+ 	arm*-semi)
+-		os=aout
++		os=
++		obj=aout
+ 		;;
+ 	c4x-* | tic4x-*)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	c8051-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	clipper-intergraph)
+ 		os=clix
+ 		;;
+ 	hexagon-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	tic54x-*)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	tic55x-*)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	tic6x-*)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	# This must come before the *-dec entry.
+ 	pdp10-*)
+@@ -1568,19 +1589,24 @@
+ 		os=sunos3
+ 		;;
+ 	m68*-cisco)
+-		os=aout
++		os=
++		obj=aout
+ 		;;
+ 	mep-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	mips*-cisco)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+-	mips*-*)
+-		os=elf
++	mips*-*|nanomips*-*)
++		os=
++		obj=elf
+ 		;;
+ 	or32-*)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	*-tti)	# must be before sparc entry or we get the wrong os.
+ 		os=sysv3
+@@ -1589,7 +1615,8 @@
+ 		os=sunos4.1.1
+ 		;;
+ 	pru-*)
+-		os=elf
++		os=
++		obj=elf
+ 		;;
+ 	*-be)
+ 		os=beos
+@@ -1670,10 +1697,12 @@
+ 		os=uxpv
+ 		;;
+ 	*-rom68k)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	*-*bug)
+-		os=coff
++		os=
++		obj=coff
+ 		;;
+ 	*-apple)
+ 		os=macos
+@@ -1691,10 +1720,11 @@
+ 
+ fi
+ 
+-# Now, validate our (potentially fixed-up) OS.
++# Now, validate our (potentially fixed-up) individual pieces (OS, OBJ).
++
+ case $os in
+ 	# Sometimes we do "kernel-libc", so those need to count as OSes.
+-	musl* | newlib* | relibc* | uclibc*)
++	llvm* | musl* | newlib* | relibc* | uclibc*)
+ 		;;
+ 	# Likewise for "kernel-abi"
+ 	eabi* | gnueabi*)
+@@ -1702,6 +1732,9 @@
+ 	# VxWorks passes extra cpu info in the 4th filed.
+ 	simlinux | simwindows | spe)
+ 		;;
++	# See `case $cpu-$os` validation below
++	ghcjs)
++		;;
+ 	# Now accept the basic system types.
+ 	# The portable systems comes first.
+ 	# Each alternative MUST end in a * to match a version number.
+@@ -1719,11 +1752,11 @@
+ 	     | mirbsd* | netbsd* | dicos* | openedition* | ose* \
+ 	     | bitrig* | openbsd* | secbsd* | solidbsd* | libertybsd* | os108* \
+ 	     | ekkobsd* | freebsd* | riscix* | lynxos* | os400* \
+-	     | bosx* | nextstep* | cxux* | aout* | elf* | oabi* \
+-	     | ptx* | coff* | ecoff* | winnt* | domain* | vsta* \
++	     | bosx* | nextstep* | cxux* | oabi* \
++	     | ptx* | ecoff* | winnt* | domain* | vsta* \
+ 	     | udi* | lites* | ieee* | go32* | aux* | hcos* \
+ 	     | chorusrdb* | cegcc* | glidix* | serenity* \
+-	     | cygwin* | msys* | pe* | moss* | proelf* | rtems* \
++	     | cygwin* | msys* | moss* | proelf* | rtems* \
+ 	     | midipix* | mingw32* | mingw64* | mint* \
+ 	     | uxpv* | beos* | mpeix* | udk* | moxiebox* \
+ 	     | interix* | uwin* | mks* | rhapsody* | darwin* \
+@@ -1736,71 +1769,119 @@
+ 	     | onefs* | tirtos* | phoenix* | fuchsia* | redox* | bme* \
+ 	     | midnightbsd* | amdhsa* | unleashed* | emscripten* | wasi* \
+ 	     | nsk* | powerunix* | genode* | zvmoe* | qnx* | emx* | zephyr* \
+-	     | fiwix* | mlibc* | cos* | mbr* )
++	     | fiwix* | mlibc* | cos* | mbr* | ironclad* | macabi)
+ 		;;
+ 	# This one is extra strict with allowed versions
+ 	sco3.2v2 | sco3.2v[4-9]* | sco5v6*)
+ 		# Don't forget version if it is 3.2v4 or newer.
+ 		;;
++	# This refers to builds using the UEFI calling convention
++	# (which depends on the architecture) and PE file format.
++	# Note that this is both a different calling convention and
++	# different file format than that of GNU-EFI
++	# (x86_64-w64-mingw32).
++	uefi)
++		;;
+ 	none)
+ 		;;
+ 	kernel* | msvc* )
+ 		# Restricted further below
+ 		;;
++	'')
++		if test x"$obj" = x
++		then
++			echo "Invalid configuration '$1': Blank OS only allowed with explicit machine code file format" 1>&2
++		fi
++		;;
+ 	*)
+ 		echo "Invalid configuration '$1': OS '$os' not recognized" 1>&2
+ 		exit 1
+ 		;;
+ esac
+ 
++case $obj in
++	aout* | coff* | elf* | pe*)
++		;;
++	'')
++		# empty is fine
++		;;
++	*)
++		echo "Invalid configuration '$1': Machine code format '$obj' not recognized" 1>&2
++		exit 1
++		;;
++esac
++
++# Here we handle the constraint that a (synthetic) cpu and os are
++# valid only in combination with each other and nowhere else.
++case $cpu-$os in
++	# The "javascript-unknown-ghcjs" triple is used by GHC; we
++	# accept it here in order to tolerate that, but reject any
++	# variations.
++	javascript-ghcjs)
++		;;
++	javascript-* | *-ghcjs)
++		echo "Invalid configuration '$1': cpu '$cpu' is not valid with os '$os$obj'" 1>&2
++		exit 1
++		;;
++esac
++
+ # As a final step for OS-related things, validate the OS-kernel combination
+ # (given a valid OS), if there is a kernel.
+-case $kernel-$os in
+-	linux-gnu* | linux-dietlibc* | linux-android* | linux-newlib* \
+-		   | linux-musl* | linux-relibc* | linux-uclibc* | linux-mlibc* )
++case $kernel-$os-$obj in
++	linux-gnu*- | linux-android*- | linux-dietlibc*- | linux-llvm*- \
++		    | linux-mlibc*- | linux-musl*- | linux-newlib*- \
++		    | linux-relibc*- | linux-uclibc*- )
+ 		;;
+-	uclinux-uclibc* )
++	uclinux-uclibc*- )
+ 		;;
+-	managarm-mlibc* | managarm-kernel* )
++	managarm-mlibc*- | managarm-kernel*- )
+ 		;;
+-	windows*-gnu* | windows*-msvc*)
++	windows*-msvc*-)
+ 		;;
+-	-dietlibc* | -newlib* | -musl* | -relibc* | -uclibc* | -mlibc* )
++	-dietlibc*- | -llvm*- | -mlibc*- | -musl*- | -newlib*- | -relibc*- \
++		    | -uclibc*- )
+ 		# These are just libc implementations, not actual OSes, and thus
+ 		# require a kernel.
+ 		echo "Invalid configuration '$1': libc '$os' needs explicit kernel." 1>&2
+ 		exit 1
+ 		;;
+-	-kernel* )
++	-kernel*- )
+ 		echo "Invalid configuration '$1': '$os' needs explicit kernel." 1>&2
+ 		exit 1
+ 		;;
+-	*-kernel* )
++	*-kernel*- )
+ 		echo "Invalid configuration '$1': '$kernel' does not support '$os'." 1>&2
+ 		exit 1
+ 		;;
+-	*-msvc* )
++	*-msvc*- )
+ 		echo "Invalid configuration '$1': '$os' needs 'windows'." 1>&2
+ 		exit 1
+ 		;;
+-	kfreebsd*-gnu* | kopensolaris*-gnu*)
++	kfreebsd*-gnu*- | kopensolaris*-gnu*-)
+ 		;;
+-	vxworks-simlinux | vxworks-simwindows | vxworks-spe)
++	vxworks-simlinux- | vxworks-simwindows- | vxworks-spe-)
+ 		;;
+-	nto-qnx*)
++	nto-qnx*-)
+ 		;;
+-	os2-emx)
++	os2-emx-)
+ 		;;
+-	*-eabi* | *-gnueabi*)
++	*-eabi*- | *-gnueabi*-)
+ 		;;
+-	none-coff* | none-elf*)
++	ios*-simulator- | tvos*-simulator- | watchos*-simulator- )
++		;;
++	ios*-macabi- )
++		;;
++	none--*)
  		# None (no kernel, i.e. freestanding / bare metal),
+-		# can be paired with an output format "OS"
++		# can be paired with an machine code file format
+ 		;;
+-	-*)
++	-*-)
+ 		# Blank kernel with real OS is always fine.
+ 		;;
+-	*-*)
++	--*)
++		# Blank kernel and OS with real machine code file format is always fine.
++		;;
++	*-*-*)
+ 		echo "Invalid configuration '$1': Kernel '$kernel' not known to work with OS '$os'." 1>&2
+ 		exit 1
+ 		;;
+@@ -1884,7 +1965,7 @@
+ 		;;
+ esac
+ 
+-echo "$cpu-$vendor-${kernel:+$kernel-}$os"
++echo "$cpu-$vendor${kernel:+-$kernel}${os:+-$os}${obj:+-$obj}"
+ exit
+ 
+ # Local variables:
